'use client';
/* oxlint-disable react/react-compiler -- The imperative simulation controller and skill store intentionally live in refs; revision state snapshots their mutations into React renders. */
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { Shield, Play, Pause, RotateCcw, Mic, ArrowUpRight, Download, BookOpen, GitBranch, Activity, Check, X, ChevronRight, Square, FlaskConical, Settings2, Volume2, VolumeX } from 'lucide-react';
import { PlatformNav } from '../components/PlatformNav';
import { DINNER_TABLE_MISSION, MISSION_STEPS, makeMissionRun, missionHref, normalizeSeed, readMissionRun, writeMissionRun } from '../lib/mission';
import { Controller } from '../../src/execution/controller';
import { ContactTestbed } from '../../src/embodiment/contact-testbed';
import { SkillLibrary } from '../../src/skills/library';
import { compile, SAFETY_LESSON, PREFERENCE_LESSON, protection } from '../../src/teaching/compiler';
import type { Contract } from '../../src/teaching/schema';
import type { World } from '../../src/aegis/world';
const TRAINING_STAGES = [
  { id: 'observe', label: 'Observe', detail: 'Run the deterministic scene and identify the next bimanual phase.' },
  { id: 'teach', label: 'Teach', detail: 'Give Aegis a correction it can compile into a checkable guardrail.' },
  { id: 'rehearse', label: 'Rehearse', detail: 'Advance the dinner-table contract and watch the hand-off responsibility.' },
  { id: 'verify', label: 'Verify', detail: 'Record symbolic safety evidence before claiming native MuJoCo evidence.' },
] as const;
const label=(s:string)=>s.replaceAll('_',' ');
const color=(s:string)=>s==='CLEAN'?'#72e4bd':s==='CONTAMINATED'?'#ff785e':s==='SUSPECT'?'#edc86d':'#a3afc2';
function save(name:string,data:string){const url=URL.createObjectURL(new Blob([data],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Scene({world}:{world:World}) {
  const objects=Object.values(world.entities);
  return <svg viewBox="0 0 760 460" aria-label="Symbolic guardrail model showing contamination quarantined away from a protected clean area">
    <title>Symbolic guardrail model showing contamination quarantined away from a protected clean area</title>
    <defs><pattern id="grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M 32 0 L 0 0 0 32" fill="none" stroke="#273442" strokeWidth=".6"/></pattern></defs>
    <rect x="0" y="0" width="760" height="460" fill="#101b25"/><rect x="24" y="24" width="712" height="412" fill="url(#grid)" stroke="#334452"/>
    <text x="40" y="48" className="svgmeta">GUARDRAIL SIDECAR / SYMBOLIC CONTACT MODEL</text><text x="40" y="419" className="svgmeta">CONTAMINATION QUARANTINED · CLEAN AREA PROTECTED · NO PHYSICS</text>
    {objects.filter(e=>e.kind==='zone').map(e=>{const x=e.pose[0]*660+48,y=e.pose[1]*330+52,clean=e.id==='clean_area';return <g key={e.id}><rect x={x-74} y={y-29} width="148" height="62" rx="5" stroke={color(e.state)} strokeWidth={clean?2:1} fill={color(e.state)} fillOpacity={clean?'.1':'.07'} strokeDasharray="5 4"/>{clean&&<rect x={x-84} y={y-39} width="168" height="82" rx="9" fill="none" stroke="#72e4bd" strokeOpacity=".35" strokeDasharray="2 6"/>}<text x={x} y={y-38} fill={color(e.state)} textAnchor="middle" fontSize="9" letterSpacing="1">{clean?'PROTECTED / CLEAN':'QUARANTINE BUFFER'}</text><text x={x} y={y+5} fill={color(e.state)} textAnchor="middle" fontSize="13">{clean?'CLEAN AREA · LOCKED':'QUARANTINE · CONTAMINATED'}</text></g>})}
    {world.edges.filter(e=>e.relation==='CONTACT').slice(-4).map((e,i)=>{const a=world.entities[e.actor],b=world.entities[e.target];return <line key={e.id} x1={a.pose[0]*660+48} y1={a.pose[1]*330+52} x2={b.pose[0]*660+48} y2={b.pose[1]*330+52} stroke={color(a.state)} strokeDasharray="4 6" opacity={.2+i*.15}/>;})}
    {objects.filter(e=>e.kind!=='zone').map(e=>{const x=e.pose[0]*660+48,y=e.pose[1]*330+52;return <g key={e.id} style={{transition:'transform .5s ease'}} transform={`translate(${x},${y})`}><circle r={e.kind==='gripper'?23:13} fill="#101b25" stroke={color(e.state)} strokeWidth={e.kind==='gripper'?3:2}/><text y="5" fill={color(e.state)} textAnchor="middle" fontSize="12">{e.kind==='gripper'?e.id[0].toUpperCase():e.protected?'S':e.kind==='tool'?'?':'C'}</text><text y={e.kind==='gripper'?42:-23} textAnchor="middle" fill="#e1eaf0" fontSize="12">{label(e.id)}</text>{e.heldBy&&<text y="31" textAnchor="middle" fill="#edc86d" fontSize="12">held</text>}</g>;})}
  </svg>;
}

function DinnerTableLearningLoop({seed,step,stage,onStage,onAdvance,onReset}:{seed:number;step:number;stage:string;onStage:(stage:string)=>void;onAdvance:()=>void;onReset:()=>void}) {
  const activeStep=MISSION_STEPS[Math.min(step,MISSION_STEPS.length-1)];
  const stageIndex=Math.max(0,TRAINING_STAGES.findIndex(item=>item.id===stage));
  return <section className="dinner-loop" aria-label="Dinner-table learning loop">
    <div className="dinner-loop-heading"><div><span className="eyebrow">DINNER-TABLE CURRICULUM · DT-01</span><h2>Train the machine to set the table.</h2><p>One shared loop from scene observation to teachable correction, bimanual rehearsal, and evidence review.</p></div><div className="dinner-loop-progress"><strong>{step}/{MISSION_STEPS.length}</strong><span>phases rehearsed</span></div></div>
    <ol className="training-stages" aria-label="Learning stages">{TRAINING_STAGES.map((item,index)=><li key={item.id}><button type="button" className={stage===item.id?'active':index<stageIndex?'complete':''} onClick={()=>onStage(item.id)}><span>{index<stageIndex?<Check size={13}/>:String(index+1).padStart(2,'0')}</span><strong>{item.label}</strong></button></li>)}</ol>
    <div className="dinner-loop-body"><div className="loop-phase"><span className="eyebrow">CURRENT DINNER-TABLE PHASE</span><strong>{step===MISSION_STEPS.length?'Table setting complete':activeStep.label}</strong><p>{step===MISSION_STEPS.length?'All six phases are staged. Review the evidence trail before presenting the result.':activeStep.detail}</p><div className="loop-responsibility"><span>{activeStep.arm} ARM</span><b>{activeStep.object.toUpperCase()}</b><small>seed {seed}</small></div></div><div className="loop-sequence" aria-label="Dinner-table task sequence">{MISSION_STEPS.map((item,index)=><div key={item.id} className={index<step?'done':index===step?'current':''}><span>{index<step?<Check size={12}/>:String(index+1).padStart(2,'0')}</span><small>{item.arm}</small><strong>{item.label.replace('Open utensil drawer','Open drawer').replace('Retrieve ','')}</strong></div>)}</div></div>
    <div className="dinner-loop-actions"><button type="button" className="primary" onClick={()=>onStage('teach')}><BookOpen size={15}/> Teach this phase</button><button type="button" onClick={onAdvance} disabled={step===MISSION_STEPS.length}><ChevronRight size={15}/> Advance rehearsal</button><button type="button" onClick={onReset}><RotateCcw size={15}/> Reset curriculum</button><span className="loop-honesty"><Activity size={14}/> Browser task model · native physics separate</span></div>
  </section>;
}

export default function Page(){
  const library=useRef<SkillLibrary|null>(null),controller=useRef<Controller|null>(null),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null);
  const [revision,setRevision]=useState(0),[skill,setSkill]=useState<Contract|null>(null),[running,setRunning]=useState(false),[seed,setSeed]=useState(1001),[count,setCount]=useState(2),[transfer,setTransfer]=useState(false),[tab,setTab]=useState('Teach'),[text,setText]=useState(''),[message,setMessage]=useState('Observe the dinner-table phase, teach a correction, then rehearse it.'),[error,setError]=useState(''),[clarification,setClarification]=useState(false),[recording,setRecording]=useState(false),[transcribing,setTranscribing]=useState(false),[voiceReady,setVoiceReady]=useState(false),[readAloud,setReadAloud]=useState(true),[voiceMuted,setVoiceMuted]=useState(true),[voices,setVoices]=useState<SpeechSynthesisVoice[]>([]),[voiceName,setVoiceName]=useState(''),[speechRate,setSpeechRate]=useState(1.04),[speechPitch,setSpeechPitch]=useState(.98),[speechVolume,setSpeechVolume]=useState(.85),[lastLesson,setLastLesson]=useState(''),[previousVersion,setPreviousVersion]=useState(''),[bench,setBench]=useState<{passed:number;total:number;violations:number}|null>(null),[missionSeed,setMissionSeed]=useState(1001),[missionStep,setMissionStep]=useState(0),[missionSource,setMissionSource]=useState<'linked'|'restored'|'default'>('default'),[loopStage,setLoopStage]=useState('observe');
  const refresh=()=>setRevision(x=>x+1);
  useEffect(()=>{const searchParams=new URLSearchParams(window.location.search);const stored=readMissionRun(window.localStorage);const requestedSeedRaw=searchParams.get('seed');const requestedStepRaw=searchParams.get('step');const requestedSeed=requestedSeedRaw===null?Number.NaN:Number(requestedSeedRaw);const requestedStep=requestedStepRaw===null?Number.NaN:Number(requestedStepRaw);const linked=searchParams.get('mission')===DINNER_TABLE_MISSION.id||searchParams.has('seed');const nextSeed=normalizeSeed(Number.isSafeInteger(requestedSeed)?requestedSeed:stored?.seed??1001);const nextStep=searchParams.has('step')?Math.min(MISSION_STEPS.length,Math.max(0,Math.floor(Number.isFinite(requestedStep)?requestedStep:0))):stored?.completedSteps??0;setMissionSeed(nextSeed);setMissionStep(nextStep);setMissionSource(linked?'linked':stored?'restored':'default');setLoopStage(nextStep===MISSION_STEPS.length?'verify':nextStep>0?'rehearse':'observe');setSeed(nextSeed);try{library.current=new SkillLibrary(localStorage);const current=library.current.current();setSkill(current);controller.current=new Controller(new ContactTestbed(nextSeed,2,false),current);refresh();}catch(e){setError(`Skill storage could not be loaded: ${String(e)}. Export or repair storage before continuing.`);}fetch('/api/speech').then(r=>r.json() as Promise<{configured:boolean}>).then(r=>setVoiceReady(r.configured)).catch(()=>setVoiceReady(false));return()=>{stream.current?.getTracks().forEach(t=>t.stop());};},[]);
  useEffect(()=>{if(!running)return;const timer=setInterval(()=>{try{const c=controller.current!;c.step();refresh();if(c.finished){setRunning(false);const result=c.result();library.current!.validate({at:new Date().toISOString(),episode:result.episode,passed:result.passed,environment:result.environment,violations:result.violations});setSkill(library.current!.current());setMessage(result.passed?'Verified: goals achieved, protected entities stayed clean.':result.failure??'Episode failed verification.');}}catch(e){setRunning(false);setError(String(e));}},650);return()=>clearInterval(timer);},[running]);
  useEffect(()=>{if(!readAloud||voiceMuted||typeof window==='undefined'||!('speechSynthesis' in window)||!message)return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(message);utterance.rate=speechRate;utterance.pitch=speechPitch;utterance.volume=speechVolume;utterance.voice=voices.find(v=>v.name===voiceName)||null;window.speechSynthesis.speak(utterance);return()=>window.speechSynthesis.cancel();},[message,readAloud,voiceMuted,speechRate,speechPitch,speechVolume,voiceName,voices]);
  useEffect(()=>{if(typeof window==='undefined'||!('speechSynthesis' in window))return;const load=()=>setVoices(window.speechSynthesis.getVoices());load();window.speechSynthesis.addEventListener('voiceschanged',load);return()=>window.speechSynthesis.removeEventListener('voiceschanged',load);},[]);
  const speak=(value=message)=>{if(voiceMuted||!readAloud||typeof window==='undefined'||!('speechSynthesis' in window)||!value)return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(value);utterance.rate=speechRate;utterance.pitch=speechPitch;utterance.volume=speechVolume;utterance.voice=voices.find(v=>v.name===voiceName)||null;window.speechSynthesis.speak(utterance);};
  const syncSeed=(value:number)=>{const next=normalizeSeed(value);setSeed(next);setMissionSeed(next);try{writeMissionRun(window.localStorage,{...(readMissionRun(window.localStorage)??makeMissionRun(next,missionStep)),seed:next,updatedAt:new Date().toISOString()});}catch{setMessage('Seed changed for this workspace. Browser storage is unavailable, so the session will not persist.');}};
  const reset=(baseline=false)=>{try{setRunning(false);const current=baseline?library.current!.versions()[0]:library.current!.current();controller.current=new Controller(new ContactTestbed(seed,count,transfer),current);setMessage(baseline?'Baseline episode uses v1.0. Your learned library is preserved.':`Scene reset. Remembered skill v${current.version} loaded.`);setError('');refresh();}catch(e){setError(String(e));}};
  const persistMissionStep=(nextStep:number,status:'ready'|'paused'|'complete'='paused')=>{try{const current=readMissionRun(window.localStorage)??makeMissionRun(missionSeed);writeMissionRun(window.localStorage,{...current,missionId:DINNER_TABLE_MISSION.id,seed:missionSeed,completedSteps:Math.min(MISSION_STEPS.length,Math.max(0,Math.floor(nextStep))),status,updatedAt:new Date().toISOString()});}catch{setMessage('The curriculum moved locally, but browser storage is unavailable for session persistence.');}};
  const advanceMission=()=>{const nextStep=Math.min(MISSION_STEPS.length,missionStep+1);persistMissionStep(nextStep,nextStep===MISSION_STEPS.length?'complete':'paused');setMissionStep(nextStep);setLoopStage(nextStep===MISSION_STEPS.length?'verify':'rehearse');setMessage(nextStep===MISSION_STEPS.length?'Dinner-table rehearsal complete. Review the evidence before presenting it.':`Rehearsal advanced to ${MISSION_STEPS[nextStep].label.toLowerCase()}.`);};
  const resetCurriculum=()=>{persistMissionStep(0,'ready');setMissionStep(0);setLoopStage('observe');reset();setMessage('Dinner-table curriculum reset to observe.');};
  const run=()=>{const c=controller.current;if(!c)return;if(c.finished){setMessage('Reset the safety rehearsal to begin another episode.');return;}c.resume();setLoopStage('rehearse');setRunning(true);};
  const teach=(input:string,source:'text'|'speechmatics'='text')=>{try{setError('');const result=compile(input);setLastLesson(input);if(result.status==='command'){if(result.command==='run'||result.command==='continue')run();if(result.command==='stop'){controller.current!.stop();setRunning(false);setMessage('Paused. No further actions will be issued.');}if(result.command==='why')setMessage(controller.current!.explain());return;}if(result.status==='clarify'){setMessage(result.question);setClarification(result.question.startsWith('Should contaminated'));return;}const old=library.current!.current();const updated=library.current!.teach(input,result.rules,source);controller.current!.teach(updated);setPreviousVersion(old.version);setSkill(updated);setLoopStage('rehearse');setMessage(`Guardrail learned for the dinner-table run. ${result.explanation}`);setClarification(false);setText('');refresh();}catch(e){setError(String(e));}};
  const confirm=()=>{try{const old=library.current!.current();const updated=library.current!.teach(`${lastLesson}\nClarified: prohibit contaminated contact with protected clean objects.`,[protection]);setPreviousVersion(old.version);setSkill(updated);controller.current!.teach(updated);setLoopStage('rehearse');setClarification(false);setMessage('Clarification recorded as a dinner-table safety guardrail.');refresh();}catch(e){setError(String(e));}};
  const record=async()=>{if(recording){recorder.current?.stop();return;}try{setError('');if(!navigator.mediaDevices||!window.MediaRecorder)throw Error('Microphone recording is unavailable in this browser.');stream.current=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream.current);recorder.current=r;const parts:BlobPart[]=[];r.ondataavailable=e=>{if(e.data.size)parts.push(e.data);};r.onstop=async()=>{stream.current?.getTracks().forEach(t=>t.stop());setRecording(false);setTranscribing(true);try{const response=await fetch('/api/speech',{method:'POST',headers:{'Content-Type':r.mimeType||'audio/webm'},body:new Blob(parts,{type:r.mimeType||'audio/webm'})});const result=await response.json() as {text?:string;error?:string;latencyMs?:number};if(!response.ok||!result.text)throw Error(result.error??'Transcription failed');teach(result.text,'speechmatics');}catch(e){setError(String(e));}finally{setTranscribing(false);}};r.start();setRecording(true);setTimeout(()=>{if(r.state==='recording')r.stop();},30000);}catch(e){stream.current?.getTracks().forEach(t=>t.stop());setError(String(e));}};
  const benchmark=()=>{try{let passed=0,violations=0;for(let i=1001;i<=1050;i++){const r=new Controller(new ContactTestbed(i,5,true),library.current!.current()).run();passed+=Number(r.passed);violations+=Number(r.violations>0);}setBench({passed,total:50,violations});setLoopStage('verify');setMessage(`Safety sidecar verification recorded ${passed}/50 passing episodes.`);}catch(e){setError(String(e));}};
  const c=controller.current;void revision;
  const activeMissionStep=MISSION_STEPS[Math.min(missionStep,MISSION_STEPS.length-1)];
  const missionContextLink=missionHref(missionSeed,missionStep);
  const missionSourceLabel=missionSource==='linked'?'LINKED FROM MISSION':missionSource==='restored'?'RESTORED SESSION':'DEFAULT SESSION';
  return <div className="shell"><aside className="rail"><div className="brandmark"><Shield size={26}/></div><span className="rail-word">FORTIFIERS</span><div className="rail-bottom">F/A<br/>01</div></aside><div className="workspace"><PlatformNav missionSeed={missionSeed} missionStep={missionStep}/>
    <main><section className="intro"><div><p className="eyebrow">DINNER-TABLE SKILL TRAINING · INTEL PHYSICAL AI</p><h1>Train the machine to<br/>set the table<span>.</span></h1></div><div className="intro-note"><span className="outline-icon"><FlaskConical size={23}/></span><div><strong>Aegis</strong><p>Bimanual dinner-table apprentice</p><small>DT-01 contract · browser loop + native evidence separate</small></div></div></section>
    {error&&<div className="error" role="alert">{error}</div>}
    <DinnerTableLearningLoop seed={missionSeed} step={missionStep} stage={loopStage} onStage={(next)=>{setLoopStage(next);if(next==='teach')setTab('Teach');}} onAdvance={advanceMission} onReset={resetCurriculum}/>
    <section className="mission-context" aria-label="Connected dinner-table mission session"><div className="mission-context-main"><span className="eyebrow">CONNECTED MISSION · {DINNER_TABLE_MISSION.shortId} · {missionSourceLabel}</span><h2>{DINNER_TABLE_MISSION.name}</h2><p>Seed <strong>{missionSeed}</strong> and the current visual phase are shared with the competition mission. This workspace teaches the policy contract; it does not claim browser physics.</p></div><div className="mission-context-phase"><span className="eyebrow">VISUAL RUN</span><strong>{missionStep===MISSION_STEPS.length?'Complete':missionStep===0?'Ready':activeMissionStep.label}</strong><small>{missionStep}/{MISSION_STEPS.length} steps complete</small></div><div className="mission-context-action"><Link href={missionContextLink}>Return to dinner table <ArrowUpRight size={15}/></Link><button type="button" onClick={()=>{setTab('Teach');setText(SAFETY_LESSON);setMessage(`Loaded a safety correction for ${activeMissionStep.label.toLowerCase()}. Teach it, then re-run this workspace testbed.`);}}>Load safe correction <ArrowUpRight size={15}/></button></div></section>
    <div className="workgrid"><section className="scene-panel"><div className="panel-heading"><div><span className="eyebrow">02 / REHEARSE SAFETY</span><h2>The guardrail sidecar</h2><p className="panel-subtitle">Quarantine contaminated material before it can enter the protected clean area.</p></div><span className={`pill ${running?'live':''}`}>{running?'RUNNING':c?.finished?'EPISODE FINISHED':'READY'}</span></div>
      <div className="scene">{c?<Scene world={c.world}/>:<div className="loading">Loading skill library…</div>}</div><div className="scene-legend"><span><i style={{background:color('CLEAN')}}/>Clean area protected</span><span><i style={{background:color('CONTAMINATED')}}/>Quarantine buffer</span><span><i style={{background:color('UNKNOWN')}}/>Unknown</span><span className="scene-step">{c?.actions??0} actions observed</span></div>
      <div className="runbar"><button className="primary" disabled={!c||running} onClick={run}><Play size={16}/> Rehearse guardrails</button><button disabled={!c} onClick={()=>{c!.stop();setRunning(false);setMessage('Paused.');}}><Pause size={16}/> Stop</button><button disabled={!c||running||c.finished} onClick={()=>{try{c!.resume();c!.step();setLoopStage('rehearse');refresh();}catch(e){setError(String(e));}}}>Step <ChevronRight size={15}/></button><button disabled={!c} onClick={()=>reset()}><RotateCcw size={16}/> Reset sidecar</button></div>
      <details className="scene-settings"><summary><Settings2 size={15}/> Scene and fault controls</summary><div className="settings-row"><label>Seed<input type="number" value={seed} onChange={e=>syncSeed(Number(e.target.value))}/></label><label>Samples<input type="number" min="1" max="12" value={count} onChange={e=>setCount(Number(e.target.value))}/></label><label className="checklabel"><input type="checkbox" checked={transfer} onChange={e=>setTransfer(e.target.checked)}/> New object identity</label></div><div className="button-row"><button onClick={()=>reset(true)} disabled={!c}>Run baseline v1.0</button><button disabled={!c||running} onClick={()=>{(c!.adapter as ContactTestbed).faults=['grasp'];setMessage('One failed grasp scheduled in the testbed.');}}>Inject failed grasp</button></div></details>
      <div className="mission"><div className="panel-heading"><div><span className="eyebrow">02 / SAFETY CONTRACT</span><h2>Guardrail checks</h2></div><span className="muted">Sidecar v{c?.contract.version??'1.0'}</span></div>{c?.tasks.map((task,i)=><div className="task" key={`${task.target}-${task.zone}`}><span className="task-number">{String(i+1).padStart(2,'0')}</span><span>Check <strong>{label(task.target)}</strong> → {label(task.zone)}</span>{c.world.entities[task.target]?.zone===task.zone?<Check size={17} className="green"/>:<span className="task-pending"/>}</div>)}<div className="decision-list">{c?.lastCandidates.map(d=><div className={d.safe?'decision':'decision blocked'} key={d.action.actor}>{d.safe?<Check size={14}/>:<X size={14}/>}<span>{label(d.action.actor)} → {label(d.action.target)}</span><small>{d.safe?`cost ${d.cost.toFixed(2)}`:d.reasons.join(', ')}</small></div>)}</div></div>
    </section><section className="teaching-panel"><div className="panel-heading"><div><span className="eyebrow">03 / TEACH & REMEMBER</span><h2>Dinner-table guardrails</h2></div><BookOpen size={22}/></div><nav className="tabs" aria-label="Knowledge views">{['Teach','Skill','Provenance','History'].map(t=><button key={t} onClick={()=>setTab(t)} aria-current={tab===t?'page':undefined} className={tab===t?'active':''}>{t}</button>)}</nav>
    {tab==='Teach'&&<><div className="teaching-copy"><h3>A table-setting correction becomes knowledge.</h3><p>Teach a safety or arm-assignment correction for the current dinner-table phase. Aegis compiles supported language into rules it can check on the next rehearsal.</p></div><form onSubmit={e=>{e.preventDefault();teach(text);}}><label className="eyebrow" htmlFor="lesson">CORRECTION FOR THIS DINNER-TABLE RUN</label><textarea id="lesson" value={text} onChange={e=>setText(e.target.value)} placeholder="Once an arm touches contaminated material, treat that arm as contaminated too…" rows={5} maxLength={4000}/><div className="teach-actions"><button className="primary" disabled={!skill||!text.trim()} type="submit">Teach Aegis <ArrowUpRight size={17}/></button><button type="button" disabled={!voiceReady||transcribing||!skill} className={recording?'recording':''} onClick={record}>{recording?<Square size={16}/>:<Mic size={16}/>} {recording?'Finish':transcribing?'Transcribing…':'Speak'}</button></div></form><p className="voice-note">{voiceReady?'Speechmatics connected. Record up to 30 seconds.': 'Speechmatics needs a server API key. Text teaching is ready.'}</p><div className="lesson-suggestions"><span className="eyebrow">TRY A DINNER-TABLE LESSON</span><button onClick={()=>setText(SAFETY_LESSON)}>Protect the cup hand-off <ArrowUpRight size={15}/></button><button onClick={()=>setText(PREFERENCE_LESSON)}>Reserve the left arm for clean placements <ArrowUpRight size={15}/></button><button onClick={()=>setText('From now on, unknown objects should be treated as suspect.')}>Treat unknown tableware as suspect <ArrowUpRight size={15}/></button></div></>}
    {tab==='Skill'&&<div className="tab-content"><p className="muted">Rules are persistent. Gripper states belong to the current episode.</p>{skill?.rules.length===0&&<p>No taught rules yet. Run a baseline, then explain contamination transfer.</p>}{skill?.rules.map(r=><article className="rule" key={r.id}><span className="eyebrow">{r.type.toUpperCase()} / {r.event}</span><h3>{label(r.id)}</h3><pre>{JSON.stringify({actor:r.actor,target:r.target,...(r.effect?{set_state:r.effect}:{cost:r.cost})},null,2)}</pre></article>)}<button onClick={()=>save('skill-library.json',library.current!.export())}><Download size={16}/> Export skill library</button><label className="import-label">Import a saved library<input type="file" accept="application/json,.json" onChange={async e=>{try{const file=e.target.files?.[0];if(!file)return;if(file.size>2*1024*1024)throw Error('Library too large');library.current!.import(await file.text());setSkill(library.current!.current());reset();}catch(err){setError(String(err));}}}/></label></div>}
    {tab==='Provenance'&&<div className="tab-content"><p className="muted">Actual discrete events from this testbed episode. Contact is not inferred from the animation.</p>{!c?.world.edges.length&&<p>No contacts recorded yet.</p>}{c?.world.edges.slice().reverse().map(edge=><article className="edge" key={edge.id}><span className="eyebrow">{edge.relation} · #{edge.sequence}</span><p>{label(edge.actor)} <span className="green">→</span> {label(edge.target)}</p><small>{edge.before.join(' / ')} → {edge.after.join(' / ')}</small></article>)}<button disabled={!c} onClick={()=>save('episode-ledger.json',JSON.stringify({world:c!.world,decisions:c!.decisions,result:c!.result()},null,2))}><Download size={16}/> Export episode ledger</button></div>}
    {tab==='History'&&<div className="tab-content">{library.current?.versions().slice().reverse().map(v=><article className="history" key={v.version}><div><GitBranch size={16}/><strong>Isolation procedure · v{v.version}</strong></div><p>{v.teachingHistory.at(-1)?.text??'Initial procedure. No contamination doctrine taught.'}</p><small>{v.validationHistory.length?`${v.validationHistory.filter(x=>x.passed).length}/${v.validationHistory.length} recorded episode validations`:'Not validated in this browser'}</small>{v.version!==skill?.version&&<button disabled={running} onClick={()=>{try{const next=library.current!.rollback(v.version);setSkill(next);c!.teach(next);setMessage(`Restored v${v.version} as new version v${next.version}.`);refresh();}catch(e){setError(String(e));}}}>Restore as new version</button>}</article>)}</div>}
    <div className="feedback" aria-live="polite"><div className="feedback-top"><span className="status-dot"/><span className="eyebrow">{lastLesson?'TEACHING RECEIVED':'APPRENTICE STATUS'}</span>{previousVersion&&<span className="version-change">v{previousVersion} → v{skill?.version}</span>}<button type="button" className="audio-toggle" aria-label={voiceMuted?'Unmute read aloud':'Mute read aloud'} onClick={()=>{setVoiceMuted(v=>!v);if(!voiceMuted)window.speechSynthesis?.cancel();}}>{voiceMuted?<VolumeX size={15}/>:<Volume2 size={15}/>} {voiceMuted?'Muted':'Mute'}</button><button type="button" className="audio-toggle" onClick={()=>setReadAloud(v=>!v)}>{readAloud?'Auto-play on':'Auto-play off'}</button><button type="button" className="audio-toggle" onClick={()=>speak()} disabled={voiceMuted}><Volume2 size={15}/> Replay</button></div>{lastLesson&&<blockquote>“{lastLesson}”</blockquote>}<p>{message}</p>{clarification&&<button onClick={confirm}>Yes, prohibit that contact</button>}<details className="voice-studio"><summary>Voice studio</summary><div className="voice-controls"><label>Voice<select value={voiceName} onChange={e=>setVoiceName(e.target.value)}><option value="">System default</option>{voices.map(v=><option key={`${v.name}-${v.lang}`} value={v.name}>{v.name} · {v.lang}</option>)}</select></label><label>Speed <output>{speechRate.toFixed(2)}×</output><input type="range" min="0.6" max="1.8" step="0.02" value={speechRate} onChange={e=>setSpeechRate(Number(e.target.value))}/></label><label>Pitch <output>{speechPitch.toFixed(2)}</output><input type="range" min="0.5" max="1.5" step="0.01" value={speechPitch} onChange={e=>setSpeechPitch(Number(e.target.value))}/></label><label>Volume <output>{Math.round(speechVolume*100)}%</output><input type="range" min="0" max="1" step="0.01" value={speechVolume} onChange={e=>setSpeechVolume(Number(e.target.value))}/></label></div></details></div>
    <div className="memory"><div><span className="eyebrow">SKILL CONTRACT</span><h3>Isolation procedure <span>v{skill?.version??'1.0'}</span></h3></div><div className="memory-stats"><span><strong>{skill?.rules.length??0}</strong> learned rules</span><span><strong>{skill?.teachingHistory.length??0}</strong> lessons</span></div></div>
    </section></div>
    <section className="evidence"><div><span className="eyebrow">04 / VERIFY</span><h2>Remember. Reset. Try again.</h2><p>Test the current skill on 50 unseen scenes with five clean samples and a different contaminated object.</p><button onClick={benchmark} disabled={!skill||running}><Activity size={16}/> Test generalization</button></div><div className="evidence-stat"><strong>{bench?`${bench.passed}/${bench.total}`:'—'}</strong><span>verified testbed episodes</span></div><div className="evidence-stat"><strong>{bench?.violations??'—'}</strong><span>episodes with safety violations</span></div><div className="evidence-note">This panel measures the symbolic teaching testbed. The dinner-table seed is shared as session context, but native MuJoCo task evidence remains separate; camera VLA inference, LeRobot, OpenVINO, and Intel hardware benchmarks remain explicit integration work.</div></section>
    <footer><span>FORTIFIERS / TEACH MACHINES THE WAY YOU TEACH PEOPLE.</span><span>Deterministic knowledge. Auditable corrections.</span></footer></main></div></div>;
}
