import { Controller } from '../src/execution/controller.ts';
import { ContactTestbed } from '../src/embodiment/contact-testbed.ts';
import { SkillLibrary, MemoryStorage } from '../src/skills/library.ts';
import { initialContract } from '../src/teaching/schema.ts';
import { compile, SAFETY_LESSON } from '../src/teaching/compiler.ts';
import { FileStorage } from './file-storage.ts';
import { mkdirSync, writeFileSync } from 'node:fs';
const N=100;
const library=new SkillLibrary(new MemoryStorage());const lesson=compile(SAFETY_LESSON);if(lesson.status!=='compiled')throw Error('Lesson did not compile');
const contract=library.teach(SAFETY_LESSON,lesson.rules);
const disk=new FileStorage('results/retention-store');disk.setItem('fortifiers.skills.v1',library.export());
const retained=new SkillLibrary(new FileStorage('results/retention-store')).current();
const cohorts=[{name:'before_learning',contract:initialContract(),start:1,count:2,transfer:false},{name:'text_only_uncompiled',contract:initialContract(),start:1,count:2,transfer:false},{name:'after_learning',contract,start:1,count:2,transfer:false},{name:'retention_reload',contract:retained,start:1,count:2,transfer:false},{name:'generalization_and_identity_transfer',contract:retained,start:1001,count:5,transfer:true}];
const episodes=cohorts.flatMap(group=>Array.from({length:N},(_,i)=>({cohort:group.name,seed:group.start+i,...new Controller(new ContactTestbed(group.start+i,group.count,group.transfer),group.contract).run()})));
const summaries=cohorts.map(group=>{const rows=episodes.filter(e=>e.cohort===group.name);return {cohort:group.name,episodes:N,successes:rows.filter(e=>e.passed).length,successRate:rows.filter(e=>e.passed).length/N,episodesWithViolations:rows.filter(e=>e.violations>0).length,safetyViolationEpisodeRate:rows.filter(e=>e.violations>0).length/N,violationEvents:rows.reduce((s,e)=>s+e.violations,0),unsafeCandidatesPrevented:rows.reduce((s,e)=>s+e.prevented,0),averageActions:rows.reduce((s,e)=>s+e.actions,0)/N,averagePlanningMs:rows.reduce((s,e)=>s+e.planningMs,0)/N,averageElapsedMs:rows.reduce((s,e)=>s+e.elapsedMs,0)/N,retries:rows.reduce((s,e)=>s+e.retries,0)};});
const report={generatedAt:new Date().toISOString(),environment:'symbolic-contact-testbed',roboticsValidated:false,speechValidated:false,corrections:1,method:'Paired seeds 1–100. Reloaded skill from disk. Held-out seeds 1001–1100 with five protected samples and amber_vial identity. Text-only ablation stores no executable rule; it is not an LLM baseline.',summaries,episodes};
mkdirSync('results',{recursive:true});writeFileSync('results/evaluation.json',JSON.stringify(report,null,2));writeFileSync('results/episodes.csv','cohort,seed,passed,violations,actions,retries,prevented,planningMs,elapsedMs\n'+episodes.map(e=>[e.cohort,e.seed,e.passed,e.violations,e.actions,e.retries,e.prevented,e.planningMs,e.elapsedMs].join(',')).join('\n'));
writeFileSync('results/SUMMARY.md',`# Measured symbolic contact results\n\nGenerated ${report.generatedAt}. These are discrete-event tests, not robotics or Intel scores. Speech latency was not measured.\n\n${report.method}\n\n| Cohort | Passed | Episodes with violations | Candidates blocked |\n|---|---:|---:|---:|\n${summaries.map(s=>`| ${s.cohort} | ${s.successes}/${N} | ${s.episodesWithViolations}/${N} | ${s.unsafeCandidatesPrevented} |`).join('\n')}\n\nOne correction. No motor dynamics, perception noise, force, collision, VLA inference or real contamination sensing is simulated. Blocked candidate counts include candidate checks, not unique real-world accidents prevented.\n`);
console.log(JSON.stringify(summaries,null,2));
